import type { Metadata } from "next";
import { ChakraProvider, Flex } from "@chakra-ui/react";
import { UserProvider } from "./providers/UserProvider";
import { ApolloProvider } from "./providers/ApolloProvider";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Flex as="body" minH="100vh" flexDirection="column">
        <ChakraProvider>
          <UserProvider>
            <ApolloProvider>
              <Header />
              {children}
              <Footer />
            </ApolloProvider>
          </UserProvider>
        </ChakraProvider>
      </Flex>
    </html>
  );
}
